on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Say hello
        id: hello
        uses: ./.github/actions/docker-action
        with: 
          who-to-greet: 'MEyyeee'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo ${{steps.hello.outputs.time}}
