name: Matrix Strategy

on:
    workflow_dispatch:

jobs:
    Build_Job:
        runs-on: ubuntu-latest
        steps:
            - name: Run a job using matrix stategy
              uses: actions/checkout@v3
