name: Pass information bw Jobs
description: Passing information between Jobs - map steps output to job output

on:
  workflow_dispatch: 
  
env:
  catcombo: kunjikanan

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step-name
        run: echo something
  test:
    runs-on: ubuntu-latest
    steps:
      - name: step-name
        run: echo something
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: step-name
        run: echo something
  sample:
    if: ${{always()}}
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.learn-context.outputs.mydog}}
      output2: ${{steps.learn-context.outputs.mycat}}
    steps:
      - name: learn context 
        id: learn-context
        run: |
          echo "mydog=blacky" >> "$GITHUB_OUTPUT"
          echo "mycat=kunji" >> "$GITHUB_OUTPUT"
      - name: testing if expression 
        if: ${{success()}}
        run: |
          echo this is ${{steps.learn-context.outputs.mycat}}
          echo ${{env.catcombo}}
          echo ${{secrets.GITHUB_TOKEN}}
  simple:
    runs-on: ubuntu-latest
    needs: sample
    steps:
      - name: learn job dependancy
        run: |
          echo ${{needs.sample.outputs.output1}}


