name: My first workflow

on:
  workflow_dispatch: 
  
env:
  name: development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step-name
        run: echo something
  test:
    runs-on: ubuntu-latest
    steps:
      - name: step-name
        run: echo something
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: step-name
        run: echo something
  sample:
    if: ${{always()}}
    runs-on: ubuntu-latest
    steps:
      - name: learn context 
        id: learn-context
        run: echo "test1=value1" >> "$GITHUB_OUTPUT"
      - name: testing if expression 
        if: ${{success()}}
        run: echo xxx

