name: My first workflow

on:
  workflow_dispatch: 

jobs:
  Build_Job:
    name: Test Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Display variables
        run: |
          echo "Hello"
          echo "Testing" ${{github.event_name}}
        
